version: "3.8"

services:
  db:
    container_name: rss-graphql-db
    build:
      context: .
    volumes:
      - rss-graphql-db-data:/var/lib/postgresql/data
    ports:
      - 5557:5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: rss-graphql-db
    restart: always

volumes:
  rss-graphql-db-data:
